version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.3.2
    volumes:
     - "/usr/share/elasticsearch/data/:/usr/share/elasticsearch/data/"
     - "./src/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      "discovery.type": "single-node"
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.2
    volumes:
      - "./src:/logjam/src"
      - "./data:/logjam/data"
      - "./src/logstash/:/usr/share/logstash/pipeline/"
    environment:
      XPACK_MONITORING_ENABLED: "false"
