version: "3.7"
services:
  elasticsearch:
    networks:
      - logjam
    image: elasticsearch:7.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      "discovery.type": "single-node"
  logstash:
    networks:
      - logjam
    image: docker.elastic.co/logstash/logstash:7.3.2
    volumes:
      - "./:/logjam"
      - "./pipeline/:/usr/share/logstash/pipeline"
    environment:
      XPACK_MONITORING_ENABLED: "false"
  kibana:
    networks:
      - logjam
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - "5601:5601"
networks:
  logjam:
