# Starts running Logjam's services, Elasticsearch & our Web Host

version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.3.2
    volumes:
       # Maps the Elasticsearch index onto the host rather than inside the container
     - "./data/elasticsearch:/usr/share/elasticsearch/data/"
       # Use Logjam's Elasticsearch configuration YAML file during setup
     - "./src/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
        # Elasticsearch's REST APIs
      - "9200:9200"
        # Elasticsearch node communication inside a cluster
      - "9300:9300"

  logjam-ui:
    build:
      context: ./src/frontend
    image: logjam-ui
    ports:
      - "80:8080"
    environment:
      "ELASTICSEARCH_HOST": "elasticsearch"
      "ELASTICSEARCH_PORT": 9200
